# Generated by Django 3.0.6 on 2020-05-30 02:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200529_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, choices=[('A', '18-'), ('B', '18-25'), ('C', '25-35'), ('D', '35-45'), ('E', '45+')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='store',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
