# Generated by Django 3.0.7 on 2020-06-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200619_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
