# Generated by Django 3.0.7 on 2020-06-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200620_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
    ]
