# Generated by Django 3.0.6 on 2020-06-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20200603_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='look',
            name='location',
        ),
        migrations.RemoveField(
            model_name='look',
            name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='look',
        ),
        migrations.AddField(
            model_name='look',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product'),
            preserve_default=False,
        ),
    ]
