# Generated by Django 3.0.6 on 2020-06-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20200606_0728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
